language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update

notifications:
  email: false

script:
  - php vendor/squizlabs/php_codesniffer/bin/phpcs rltam.php
  - php vendor/phpunit/phpunit/phpunit tests/

